2018-12-18 14:35:14 INFO run.py:213 GNS3 server version 2.1.11
2018-12-18 14:35:14 INFO run.py:215 Copyright (c) 2007-2018 GNS3 Technologies Inc.
2018-12-18 14:35:14 INFO run.py:218 Config file /home/archer/.config/GNS3/gns3_server.conf loaded
2018-12-18 14:35:14 WARNING run.py:224 Local mode is enabled. Beware, clients will have full control on your filesystem
2018-12-18 14:35:14 INFO run.py:232 Running with Python 3.7.1 and has PID 6781
2018-12-18 14:35:14 INFO run.py:79 Current locale is en_US.UTF-8
2018-12-18 14:35:14 INFO web_server.py:283 Starting server on 127.0.0.1:3080
2018-12-18 14:35:14 INFO __init__.py:65 Load controller configuration file /home/archer/.config/GNS3/gns3_controller.conf
2018-12-18 14:35:14 INFO __init__.py:168 Start controller
2018-12-18 14:35:14 INFO compute.py:79 Create compute local
2018-12-18 14:35:14 INFO compute.py:420 Connecting to compute 'local'
2018-12-18 14:35:14 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:14 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:14 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:14 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 551970 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:14 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:14 +0000] "GET /v2/appliances HTTP/1.1" 200 2558 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:14 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:14 +0000] "GET /v2/computes HTTP/1.1" 200 585 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 551970 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/appliances HTTP/1.1" 200 2558 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/projects HTTP/1.1" 200 775 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/version HTTP/1.1" 200 227 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/projects HTTP/1.1" 200 775 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'fortinet.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/fortinet.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'ostinato-3d-icon.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/ostinato-3d-icon.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol ':/symbols/guest.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/guest.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/router.svg/raw HTTP/1.1" 200 11037 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'loadbalancer.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/loadbalancer.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/multilayer_switch.svg/raw HTTP/1.1" 200 21517 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'mgmt_station.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/mgmt_station.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'linux_guest.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/linux_guest.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/firewall.svg/raw HTTP/1.1" 200 9626 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/wlan_controller.svg/raw HTTP/1.1" 200 261470 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'juniper-vqfx.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/juniper-vqfx.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'mgmt_station_docker.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/mgmt_station_docker.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'securityonion-logo.png'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/securityonion-logo.png/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'ethernet_switch.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/ethernet_switch.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'cisco-ise.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/cisco-ise.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/asa.svg/raw HTTP/1.1" 200 18812 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/ids.svg/raw HTTP/1.1" 200 13373 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'firefox.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/firefox.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/cloud.svg/raw HTTP/1.1" 200 27982 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'pan-vm-fw.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/pan-vm-fw.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'cisco-fmcv.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/cisco-fmcv.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'juniper-vmx.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/juniper-vmx.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'microsoft.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/microsoft.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 WARNING symbols.py:94 Could not retrieve symbol 'vRIN.svg'
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/vRIN.svg/raw HTTP/1.1" 200 18843 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/router_firewall.svg/raw HTTP/1.1" 200 50061 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/vpcs_guest.svg/raw HTTP/1.1" 200 19495 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/ethernet_switch.svg/raw HTTP/1.1" 200 9273 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/hub.svg/raw HTTP/1.1" 200 7636 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/frame_relay_switch.svg/raw HTTP/1.1" 200 10027 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:15 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:15 +0000] "GET /v2/symbols/:/symbols/atm_switch.svg/raw HTTP/1.1" 200 9959 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:16 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:16 +0000] "GET /v2/computes HTTP/1.1" 200 585 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:16 INFO compute.py:420 Connecting to compute 'local'
2018-12-18 14:35:16 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:16 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:35:18 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:18 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:20 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:20 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:22 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:22 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:22 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:22 +0000] "POST /v2/projects HTTP/1.1" 201 687 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:22 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:22 +0000] "POST /v2/settings HTTP/1.1" 201 1472 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:22 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:22 +0000] "POST /v2/settings HTTP/1.1" 201 1472 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:22 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:22 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 551970 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:22 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:22 +0000] "GET /v2/appliances HTTP/1.1" 200 2558 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:22 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:22 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 551970 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:22 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:22 +0000] "GET /v2/appliances HTTP/1.1" 200 2558 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:23 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:23 +0000] "GET /v2/computes HTTP/1.1" 200 1023 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:27 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:27 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 551970 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:27 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:27 +0000] "GET /v2/appliances HTTP/1.1" 200 2558 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:27 INFO project.py:81 Project 45525d6a-9772-4cf7-9187-fb6f451af4aa with path '/home/archer/GNS3/projects/Test' created
2018-12-18 14:35:27 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:27 +0000] "POST /v2/compute/projects HTTP/1.1" 201 299 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:35:27 INFO base_node.py:261 VPCS: PC-1 [8e194008-5d8d-4aee-a1a3-4ff089879c50] created
2018-12-18 14:35:27 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:27 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes HTTP/1.1" 201 568 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:35:27 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:27 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/appliances/19021f99-e36f-394d-b4a1-8aaa902ab9cc HTTP/1.1" 201 233 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:27 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:27 +0000] "PUT /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50 HTTP/1.1" 200 1392 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:35:31 INFO base_node.py:711 VPCS: 'PC-1' [8e194008-5d8d-4aee-a1a3-4ff089879c50]:local UDP tunnel created between port 10000 and 10001
2018-12-18 14:35:31 INFO vpcs_vm.py:232 Starting VPCS: ['/usr/bin/vpcs', '-p', '5001', '-m', '0', '-i', '1', '-F', '-R', '-s', '10000', '-c', '10001', '-t', '127.0.0.1', 'startup.vpc']
2018-12-18 14:35:31 INFO vpcs_vm.py:234 Logging to /home/archer/GNS3/projects/Test/project-files/vpcs/8e194008-5d8d-4aee-a1a3-4ff089879c50/vpcs.log
2018-12-18 14:35:31 ERROR route.py:210 Node error detected: NodeError
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gns3server/web/route.py", line 195, in control_schema
    yield from func(request, response)
  File "/usr/lib/python3.7/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 158, in start
    yield from vm.start()
  File "/usr/lib/python3.7/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 247, in start
    yield from self._start_ubridge()
  File "/usr/lib/python3.7/site-packages/gns3server/utils/asyncio/__init__.py", line 161, in wrapper
    return (yield from f(oself, *args, **kwargs))
  File "/usr/lib/python3.7/site-packages/gns3server/compute/base_node.py", line 531, in _start_ubridge
    raise NodeError("uBridge is not available, path doesn't exist, or you just installed GNS3 and need to restart your user session to refresh user permissions.")
gns3server.compute.error.NodeError: uBridge is not available, path doesn't exist, or you just installed GNS3 and need to restart your user session to refresh user permissions.
2018-12-18 14:35:31 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:31 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 409 446 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:35:31 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:35:31 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 409 403 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:36:18 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:36:18 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:36:37 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:36:37 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 200 659 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:36:37 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:36:37 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 200 1398 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:36:54 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:36:54 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 200 659 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:36:54 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:36:54 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/start HTTP/1.1" 204 222 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:05 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:05 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 200 659 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:05 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:05 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/start HTTP/1.1" 204 222 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:09 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:09 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 200 659 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:09 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:09 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/start HTTP/1.1" 204 222 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:13 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:13 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 200 659 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:13 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:13 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 200 1398 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:25 INFO vpcs_vm.py:314 Stopping VPCS instance PC-1 PID=6820
2018-12-18 14:37:25 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:25 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/stop HTTP/1.1" 204 244 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:25 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:25 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/stop HTTP/1.1" 204 221 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:28 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:28 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 551970 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:28 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:28 +0000] "GET /v2/appliances HTTP/1.1" 200 2558 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:28 INFO base_node.py:261 VPCS: PC-2 [2933875b-b31a-4754-870a-8c475d6347aa] created
2018-12-18 14:37:28 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:28 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes HTTP/1.1" 201 568 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:28 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:28 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/appliances/19021f99-e36f-394d-b4a1-8aaa902ab9cc HTTP/1.1" 201 233 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:28 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:28 +0000] "PUT /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/2933875b-b31a-4754-870a-8c475d6347aa HTTP/1.1" 200 1391 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:31 INFO vpcs_vm.py:232 Starting VPCS: ['/usr/bin/vpcs', '-p', '5001', '-m', '0', '-i', '1', '-F', '-R', '-s', '10000', '-c', '10001', '-t', '127.0.0.1', 'startup.vpc']
2018-12-18 14:37:31 INFO vpcs_vm.py:234 Logging to /home/archer/GNS3/projects/Test/project-files/vpcs/8e194008-5d8d-4aee-a1a3-4ff089879c50/vpcs.log
2018-12-18 14:37:31 INFO base_node.py:711 VPCS: 'PC-2' [2933875b-b31a-4754-870a-8c475d6347aa]:local UDP tunnel created between port 10002 and 10003
2018-12-18 14:37:31 INFO vpcs_vm.py:232 Starting VPCS: ['/usr/bin/vpcs', '-p', '5003', '-m', '1', '-i', '1', '-F', '-R', '-s', '10002', '-c', '10003', '-t', '127.0.0.1', 'startup.vpc']
2018-12-18 14:37:31 INFO vpcs_vm.py:234 Logging to /home/archer/GNS3/projects/Test/project-files/vpcs/2933875b-b31a-4754-870a-8c475d6347aa/vpcs.log
2018-12-18 14:37:31 ERROR route.py:210 Node error detected: NodeError
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gns3server/web/route.py", line 195, in control_schema
    yield from func(request, response)
  File "/usr/lib/python3.7/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 158, in start
    yield from vm.start()
  File "/usr/lib/python3.7/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 247, in start
    yield from self._start_ubridge()
  File "/usr/lib/python3.7/site-packages/gns3server/utils/asyncio/__init__.py", line 161, in wrapper
    return (yield from f(oself, *args, **kwargs))
  File "/usr/lib/python3.7/site-packages/gns3server/compute/base_node.py", line 534, in _start_ubridge
    raise NodeError("uBridge requires root access or the capability to interact with network adapters")
gns3server.compute.error.NodeError: uBridge requires root access or the capability to interact with network adapters
2018-12-18 14:37:31 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:31 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/start HTTP/1.1" 409 387 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:31 ERROR route.py:210 Node error detected: NodeError
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gns3server/web/route.py", line 195, in control_schema
    yield from func(request, response)
  File "/usr/lib/python3.7/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 158, in start
    yield from vm.start()
  File "/usr/lib/python3.7/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 247, in start
    yield from self._start_ubridge()
  File "/usr/lib/python3.7/site-packages/gns3server/utils/asyncio/__init__.py", line 161, in wrapper
    return (yield from f(oself, *args, **kwargs))
  File "/usr/lib/python3.7/site-packages/gns3server/compute/base_node.py", line 534, in _start_ubridge
    raise NodeError("uBridge requires root access or the capability to interact with network adapters")
gns3server.compute.error.NodeError: uBridge requires root access or the capability to interact with network adapters
2018-12-18 14:37:31 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:31 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/2933875b-b31a-4754-870a-8c475d6347aa/start HTTP/1.1" 409 387 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:31 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:31 +0000] "POST /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/nodes/start HTTP/1.1" 409 334 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:52 INFO server_handler.py:53 Start shutting down the server
2018-12-18 14:37:52 INFO vpcs_vm.py:314 Stopping VPCS instance PC-2 PID=8260
2018-12-18 14:37:52 INFO vpcs_vm.py:314 Stopping VPCS instance PC-1 PID=8255
2018-12-18 14:37:53 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:53 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/2933875b-b31a-4754-870a-8c475d6347aa/stop HTTP/1.1" 204 244 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:53 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:53 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/vpcs/nodes/8e194008-5d8d-4aee-a1a3-4ff089879c50/stop HTTP/1.1" 204 244 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:53 INFO base_node.py:313 VPCS: 'PC-1' [8e194008-5d8d-4aee-a1a3-4ff089879c50]: is closing
2018-12-18 14:37:53 INFO base_node.py:313 VPCS: 'PC-2' [2933875b-b31a-4754-870a-8c475d6347aa]: is closing
2018-12-18 14:37:53 INFO project.py:367 Project 45525d6a-9772-4cf7-9187-fb6f451af4aa with path '/home/archer/GNS3/projects/Test' closed
2018-12-18 14:37:53 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:53 +0000] "POST /v2/compute/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/close HTTP/1.1" 204 224 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:53 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:53 +0000] "POST /v2/shutdown HTTP/1.1" 201 194 "-" "GNS3 QT Client v2.1.11"
2018-12-18 14:37:55 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:55 +0000] "GET /v2/projects/45525d6a-9772-4cf7-9187-fb6f451af4aa/notifications/ws HTTP/1.1" 408 560 "-" "-"
2018-12-18 14:37:55 INFO helpers.py:529 127.0.0.1 [18/Dec/2018:13:37:55 +0000] "GET /v2/compute/notifications/ws HTTP/1.1" 200 478 "-" "Python/3.7 aiohttp/2.3.9"
2018-12-18 14:37:55 INFO __init__.py:222 Stop controller
2018-12-18 14:37:55 INFO run.py:261 Remove PID file /home/archer/.config/GNS3/gns3_server.pid
